#!/bin/zsh

y=$(tput setaf 11)
w=$(tput setaf 15)
rc=$(tput sgr0)
echo "${y}(not as fake) qcomp${rc}"
# no args
[ $# -eq 0 ] && { echo "usage: qcomp [folder] [output]"; exit 1; }
# non existent input dir arg
[ ! -d "$1" ] && { echo "invalid path"; exit 1; }
indir=$1; find=/usr/bin/find
# >:(

# check for manually specified output
outdir="${2:-$1_build}/"
[ ! "$(dirname "$0")" = "." ] && bin="$(realpath "$0")/" || bin="$(which "$0")/"
								#???						# required when script is pathed
#thx luke / https://stackoverflow.com/a/21913843

bin=$(dirname "$bin"); wbin=$(cygpath -w "$bin"); NL=$'\n'; nul=/dev/null
echo "${y}*****  Q COMPILATION   *****${rc}"

(cd "$indir" && $find * -type f -name "*.q") | while read -r f; do
	out="$outdir${f%%.*}.qb.xen"
	# (re)compile files after being modified / or if they're new
	if [ ! -f "$out" ] || [ "$out" -ot "$indir/$f" ]; then
		mkdir -p "${outdir}$(dirname $f)"
		echo "${w}Compiling $f...${rc}"
		node "$wbin/QBC/QBC.js" c -g gh3 "$indir/$f" -o "$out"
	fi
done

echo done...

