#!/bin/sh

# no args
[ $# -eq 0 ] && { echo -e "enter a path to decompile"; exit 1; }
# non existent dir arg
[ ! -d "$1" ] && { echo "invalid path"; exit 1; }
indir=$1; find=/usr/bin/find; outdir=decomp/
[ -z "$2" ] && outdir="$1_decomp/" || outdir="$2/"
rm "$outdir" -rf
[ ! "$(dirname "$0")" = "." ] && bin="$(realpath "$0")/" || bin="$(which "$0")/"
								#???						# required when script is pathed
bin=$(dirname "$bin")
wbin=$(cygpath -w "$bin")
NL=$'\n'
nul=/dev/null

INPUTS=$(pushd "$indir" > $nul && $find * -type f -name "*.qb.xen" && popd > $nul)
for f in $INPUTS
do
	mkdir -p "${outdir}$(dirname $f)"
	echo -e "Decompiling $f..."
	out="$outdir${f%%.*}.q"
	node "$wbin/QBC/QBC.js" d -g gh3 "$indir/$f" -o "$out"
	unexpand -t 4 "$out" | sed 's/[ \t]*$//' > tmp
	mv tmp "$out" -f
	# |:|
done

