#!/bin/sh

# no args
if [ $# -eq 0 ]; then
	echo -e "enter a path to decompile"
	exit 1
fi
# non existent dir arg
if [ ! -d "$1" ]; then
	echo invalid path
	exit 1
fi
indir=$1
find=/usr/bin/find
outdir=decomp/
rm "$outdir" -rf
if	[ ! "$(dirname "$0")" = "." ]; then
	bin=$(realpath "$0")/ # ???
else
	bin=$(which "$0")/ # required when script is pathed
fi
bin=$(dirname "$bin")
wbin=$(cygpath -w "$bin")
NL=$'\n'
nul=/dev/null

INPUTS=$(pushd "$indir" > $nul && $find * -type f -name "*.qb.xen" && popd > $nul)
for f in $INPUTS
do
	mkdir -p "${outdir}$(dirname $f)"
	echo -e "Decompiling $f..."
	out="$outdir${f%%.*}.q"
	node "$wbin/QBC/QBC.js" d -g gh3 "$indir/$f" -o "$out"
	unexpand -t 4 "$out" | sed 's/[ \t]*$//' > tmp
	mv tmp "$out" -f
	# |:|
done

