#!/bin/sh

# rename extracted from qb.pak (using queenbee :/  ) and put into respective folders
INPUTS=$(find . -maxdepth 1 -type f -name "*.qb")
for f in $INPUTS
do
	echo moving $f
	dir=""
	IFS='#' read -ra Q <<< "$f"
	for i in "${Q[@]}"; do
		dir=$(echo $dir$i\\)
		lastname=$i
	done
	mkdir "$dir..\\" 2>/dev/null
	mv $f "$dir..\\$i"
done

