
!define TITLEVER "FastGH3 1.1"
!define APPVER_REL 1
!define APPVER_MAJOR 1
!define APPVER_MINOR 043
!define APPVER_FIX 0
!define APPVERSION ${APPVER_REL}.${APPVER_MAJOR}.${APPVER_MINOR}.${APPVER_FIX}
