//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastGH3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastGH3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any supported files|*.chart;*.mid;*.fsp;*.zip;*.7z;*.rar;*.pak.xen|All chart types|*.chart;*.mid|FastGH3 Song Package|*.fsp;*.zip;*.7z;*.rar|Any type|*.*.
        /// </summary>
        internal static string chartFilter {
            get {
                return ResourceManager.GetString("chartFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adituv           - QbScript reverse engineering,
        ///                   compiler/decompiler,
        ///                   vsync flame fix,
        ///                   built in QB decompiler
        ///ExileLord        - GH3+ and executable reverse engineering,
        ///                   open and tap notes,
        ///                   ChartEdit/Chart-to-PAK classes and conversion tools,
        ///donnaken15       - other QbScript hacking,
        ///                   mod creation and setup,
        ///                   game optimization,
        ///                   main program and auto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning,DifficultyUp,DoubleNotes,LeftyNotes,BrokenString,WhammyAttack,PowerUpSteal.
        /// </summary>
        internal static string powersDefaultKey {
            get {
                return ResourceManager.GetString("powersDefaultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// Welcome to FastGH3 v1.0
        /// FastGH3 is an advanced mod of
        /// Guitar Hero 3 designed to be played
        /// as fast as possible. With this mod, you
        /// can play customs without any technical
        /// setup, and even associate chart or mid
        /// files with the game so you can access
        /// your charts quickly.
        ///
        /// To access the options, use
        /// the -settings parameter or
        /// open settings.bat.
        ///
        /// Press any key to load a chart..
        /// </summary>
        internal static string splashText {
            get {
                return ResourceManager.GetString("splashText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /!\ Error adding a starpower phrase. If this message appears more than once, there may be a problem.
        /// </summary>
        internal static string SPwarn {
            get {
                return ResourceManager.GetString("SPwarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;r&gt;
        ///&lt;s id=&quot;Video.Width&quot;&gt;1024&lt;/s&gt;
        ///&lt;s id=&quot;Video.Height&quot;&gt;768&lt;/s&gt;
        ///&lt;s id=&quot;Sound.SongSkew&quot;&gt;-0.1&lt;/s&gt;
        ///&lt;/r&gt;.
        /// </summary>
        internal static string xmlDefault {
            get {
                return ResourceManager.GetString("xmlDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extractor returned a non-zero error code. This could mean that the extraction has failed..
        /// </summary>
        internal static string Z7_f {
            get {
                return ResourceManager.GetString("Z7_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Z is not supported by UnRAR, unless you have 7-Zip installed, or manually extract the 7Z using the WinRAR interface..
        /// </summary>
        internal static string Z7_u {
            get {
                return ResourceManager.GetString("Z7_u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported archive type, unless you have 7-Zip or WinRAR or UnRAR installed..
        /// </summary>
        internal static string Z7_uu {
            get {
                return ResourceManager.GetString("Z7_uu", resourceCulture);
            }
        }
    }
}
